name: Testing Conditions

on: 
  workflow_dispatch:
    inputs:
      failstep:
        description: 'Job1 fail (Yes/No)?'
        required: true
        default: no
        
jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        if: ${{github.ref == 'refs/heads/master'}}
        uses: actions/checkout@v2
        
        
      - name: YES was passed as workflow input
        if: github.event.inputs.failstep == 'yes'
        run: echo "Value passed by workflow_dispatch is YES to fail workflow." 

      - name: NO was passed as workflow input
        run: echo "Value passed by workflow_dispatch is NO to fail workflow." 
        if: github.event.inputs.failstep == 'no'  
        
